### PR TITLE
fix: shell wrapper overwrites $SHELL

### LINKED ISSUE #579: VSCode server does not respect my default shell setting
## Bug description

I adopted [option 1](https://nix-community.github.io/NixOS-WSL/how-to/vscode.html) to enable vscode server in wsl. But when I open the terminal in vscode, it goes to `sh` instead of `bash` which I actually set as default.
Inside wsl, `$SHELL` is `/run/current-system/sw/bin/bash`. However, in vscode, `$SHELL` becomes `/nix/store/sh4d0lnbrapnqjsn1jwb4r07lmwirc8c-sh/bin/sh`.

## To Reproduce
Here is what I set in modules:
```nix
nixos-wsl.nixosModules.default
({ pkgs, ...}: {
  system = {
    stateVersion = "24.05";
  };

  programs.nix-ld = {
      enable = true;
      package = pkgs.nix-ld-rs;
  };

  wsl = {
    enable = true;
    useWindowsDriver = true; 
    defaultUser = "${specialArgs.username}";
  };
})
```
and this is how I set my default shell:
```nix
environment.shells = with pkgs; [
  bash
];
users.defaultUserShell = pkgs.bash;
```

## Logs
I don't know if it's related but I printed the `$PATH` in vscode's integrated terminal anyway.
```sh
sh-5.2$ echo $PATH
/home/yang/.vscode-server/bin/384ff7382de624fb94dbaf6da11977bba1ecd427/bin/remote-cli:/usr/lib/wsl/lib/:/home/yang/bin:/home/yang/.local/bin:/run/wrappers/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/home/yang/.nix-profile/bin:/nix/profile/bin:/home/yang/.local/state/nix/profile/bin:/etc/profiles/per-user/yang/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/Microsoft SQL Server/150/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Users/fyang/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/fyang/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/fyang/.dotnet/tools:/nix/store/nswmyag3qi9ars0mxw5lp8zm0wv5zxld-systemd-255.9/bin:/nix/store/3jc4m5gwimj4mbm01ijgkm2di8hiy5l3-gnugrep-3.11/bin:/nix/store/nswmyag3qi9ars0mxw5lp8zm0wv5zxld-systemd-255.9/bin:/nix/store/3jc4m5gwimj4mbm01ijgkm2di8hiy5l3-gnugrep-3.11/bin:/nix/store/nswmyag3qi9ars0mxw5lp8zm0wv5zxld-systemd-255.9/bin:/nix/store/3jc4m5gwimj4mbm01ijgkm2di8hiy5l3-gnugrep-3.11/bin
```

## WSL version

```
WSL Version： 2.3.24.0
Kernel version： 5.15.153.1-2
WSLg version： 1.0.59
MSRDC version： 1.2.5620
Direct3D version： 1.611.1-81528511
DXCore version： 10.0.26100.1-240331-1435.ge-release
Windows version： 10.0.22631.4317
```

### PR DESCRIPTION
**Pull request by nzbr**
Fixes #579

### CODE REVIEW

File: utils/src/shell_wrapper.rs [hunk 1]
```diff
@@ -18,7 +18,10 @@ fn real_main() -> anyhow::Result<()> {
     let shell = read_link(exe_dir.join("shell")).context("when locating the wrapped shell")?;
 
     // Set the SHELL environment variable to the wrapped shell instead of the wrapper
-    env::set_var("SHELL", &shell);
+    let shell_env = env::var("SHELL").unwrap_or_default();
+    if shell_env == exe.to_str().unwrap() {
```
Comment (K900) [inline utils/src/shell_wrapper.rs:22]: Can do `var_os` here to avoid the conversions.

File: utils/src/shell_wrapper.rs [hunk 2]
```diff
@@ -18,7 +18,10 @@ fn real_main() -> anyhow::Result<()> {
     let shell = read_link(exe_dir.join("shell")).context("when locating the wrapped shell")?;
 
     // Set the SHELL environment variable to the wrapped shell instead of the wrapper
-    env::set_var("SHELL", &shell);
+    let shell_env = env::var_os("SHELL").unwrap_or_default();
+    if shell_env == exe {
```
Comment (K900) [inline utils/src/shell_wrapper.rs:22]: Maybe remove `unwrap_or_default` and `shell_env == Some(exe)`?
